package no.sumo.api.exception;

/**
 * Provides a set of application error codes
 */
public enum Errorcode {
	UNKNOWN(Category.GENERAL),
	GENERAL(Category.GENERAL),
    GENERAL_NOT_FOUND(Category.GENERAL),
	NOT_AUTHORIZED(Category.GENERAL),
	
	URL_NOT_FOUND(Category.GENERAL),
	INVALID_XML(Category.GENERAL),
	INVALID_DATE(Category.GENERAL),
	
	/**
	 * When a user tries to execute an action 
	 * and does not have the required permission 
	 */
	PERMISSION_DENIED(Category.GENERAL),
	
	INVALID_PLATFORM(Category.PLATFORM),
	DUPLICATE_PLATFORM_IDENTIFIER(Category.PLATFORM),
	PLATFORM_NOT_FOUND(Category.PLATFORM),
	
	ASSET_ITEM_NOT_FOUND(Category.NOT_FOUND),
	
	/**
	 * The assetId of assetItemId is invalid
	 * 
	 */
	ASSET_ITEM_INVALID_ID(Category.ASSET_ITEM),
	ASSET_ITEM_INVALID_DURATION(Category.ASSET_ITEM),
	/**
	 * The asset has to be indexed
	 */
	ASSET_ITEM_NOT_PUBLISHED(Category.ASSET_ITEM),
	
	ASSET_COMMENT_NOT_FOUND(Category.NOT_FOUND),
	ASSET_RATING_NOT_FOUND(Category.NOT_FOUND),
	ASSET_RATING_PREMATURE(Category.ASSET),
	ASSET_PROPERTY_NOT_FOUND(Category.NOT_FOUND),
	
	USER_NOT_FOUND(Category.USER),
	USER_INVALID_USERNAME(Category.USER),
	USER_INVALID_PASSWORD(Category.USER),
	USER_INVALID_EMAIL(Category.USER),
	USER_INVALID_CREDENTIALS(Category.USER),
	USER_INVALID_MOBILENUMBER(Category.USER),
	USER_CREATION_FAILED(Category.USER),
	INVALID_REGISTRATION_DATA(Category.USER),
	USER_USERNAME_NOT_UNIQUE(Category.USER),
	USER_MULTIPLE_VALIDATION_ERRORS(Category.USER),
    USER_INVALID_PIN(Category.USER),
	
	/**
	 * No category was found
	 */
	CATEGORY_NOT_FOUND(Category.CATEGORY),
	CATEGORY_INVALID_ID(Category.CATEGORY),
	CATEGORY_SECTION_NOT_FOUND(Category.CATEGORY),
	CATEGORY_NOT_PUBLISHED(Category.CATEGORY),
    CATEGORY_INVALID_MISSING_TITLE(Category.CATEGORY),
    CATEGORY_INVALID_PROGRAM_TYPE_NOT_FOUND(Category.CATEGORY),
	AUTHENTICATION_OK(Category.AUTHENTICATION),
	AUTHENTICATION_FAILED(Category.AUTHENTICATION), 
	SESSION_NOT_AUTHENTICATED(Category.AUTHENTICATION),
	SESSION_AUTHENTICATED(Category.AUTHENTICATION),
	SESSION_INVALIDATED(Category.AUTHENTICATION),
	
	/**
	 * <b>Deprecated.</b> Use {@link #SESSION_INVALIDATED} instead
	 */
	@Deprecated 
	SESSION_INVALIDATION_OK(Category.AUTHENTICATION),
	UNAUTHORIZED(Category.AUTHENTICATION),
	INVALID_TOKEN(Category.AUTHENTICATION),
	KICKED_SESSION(Category.AUTHENTICATION),
	UNTRUSTED_PROXY(Category.AUTHENTICATION),
	
	ASSET_INVALID_DURATION(Category.ASSET),
	/**
	 * Encoder start time is missing.
	 */
	ASSET_ENCODER_START_TIME_MISSING(Category.ASSET),
	/**
	 * No asset was found
	 */
	ASSET_NOT_FOUND(Category.ASSET),
	ASSET_CATEGORY_INVALID(Category.ASSET),
	ASSET_FAILED_CREATE(Category.ASSET),
	/**
	 * The asset is not published on the requested platform.
	 */
	ASSET_NOT_PUBLISHED(Category.ASSET),
	ASSET_PLAYBACK_INVALID_GEO_LOCATION(Category.ASSET),
	ASSET_NO_ACCESS(Category.ASSET),
	ASSET_PLAYBACK_INVALID_VIDEO_FORMAT (Category.ASSET),
	ASSET_INVALID_LOG_DATA (Category.ASSET),
	ASSET_EXPIRED_LOG_DATA (Category.ASSET),

    ASSET_RELATION_TYPE_NOT_FOUND(Category.ASSET),
    ASSET_RELATION_NOT_FOUND(Category.ASSET),

    METADATA_DEFINITION_NOT_FOUND(Category.NOT_FOUND),
	
	PRODUCT_GROUP_INVALID(Category.PRODUCT_GROUP),
	PRODUCT_GROUP_NOT_FOUND(Category.PRODUCT_GROUP),
	PRODUCT_GROUP_ACCESS_NOT_FOUND(Category.PRODUCT_GROUP),
    PRODUCT_GROUP_ACCESS_INVALID(Category.PRODUCT_GROUP),
	PRODUCT_NOT_FOUND(Category.PRODUCT),
    PRODUCT_INVALID(Category.PRODUCT),
    PAYMENT_PROVIDER_NOT_FOUND(Category.PRODUCT),
	PRODUCT_PAYMENT_INVALID(Category.PRODUCT),
	PRODUCT_PAYMENT_NOT_FOUND(Category.PRODUCT),
	PRODUCT_PAYMENT_MISSING(Category.PRODUCT),
    PROGRAM_TYPE_INVALID(Category.PRODUCT),
    PROGRAM_TYPES_TREE_NOT_FOUND(Category.PRODUCT),
	THIRDPARTY_ERROR(Category.NOT_FOUND),
	REMOTE_GATEWAY(Category.GATEWAY),
	
	INVALID_PAYMENT_INFO(Category.PAYMENT),
	PAYMENT_ERROR(Category.PAYMENT), 
	PAYMENT_INPUT_MISSING (Category.PAYMENT),

	ORDER_NOT_FOUND(Category.PAYMENT),
    CATEGORY_RATING_NOT_FOUND(Category.NOT_FOUND),
    CHANNEL_NOT_FOUND(Category.NOT_FOUND),
    DISTRIBUTION_CHANNEL_NOT_FOUND(Category.NOT_FOUND),
    PROGRAM_TYPE_NOT_FOUND(Category.NOT_FOUND), CATEGORY_INVALID_PARENT_ID_NOT_FOUND(Category.CATEGORY);
	
	/**
	 * Provides categories for the various error codes. 
	 * This is only used for documentation purposes
	 */
	public enum Category { GENERAL, NOT_FOUND, CATEGORY, ASSET, ASSET_ITEM, AUTHENTICATION, USER, PRODUCT, PRODUCT_GROUP, 
		PLATFORM, GATEWAY, PAYMENT }
	
	Errorcode(Category category){
		this.category = category;	
	}
	private final Category category;
	
	public Category getCategory() {
		return category;
	}
}
