package no.sumo.api.entity.sumo.enums;

public enum SSOStatus {
	USER_NOT_MERGED, EMAIL_VERIFICATION_FAILED, MEMBER_ID_NOT_SAVED_TO_SSO, NICK_GENERATION_FAILED, MEMBER_ID_NOT_UPDATED_TO_SUMO, ATTEMPTED_NULL_UPDATE
}
