package no.sumo.api.entity.vman.enums;

public enum ProgramSortBy {
	DATE_ASC,
	DATE_DESC,
	NAME,
	NAME_DESC,
	PRIORITY,
	COUNT,
	RATING,
	RATINGCOUNT,
	VIEW_ASC,
	VIEW_DESC,
	NODEID_ASC,
	NODEID_DESC,
	EXPIRYDATE_ASC,
	EXPIRYDATE_DESC,
	PUBLISDATE_ASC,
	PUBLISDATE_DESC,
	ASSET_TITLE,
	ASSET_TITLE_DESC,
	CATEGORY_NAME,
	CATEGORY_NAME_DESC,
	CATEGORY_RATING_COUNT,

	CHANNEL_VIEW_COUNT,
	CHANNEL_PUBLISHED_DATE,
	CHANNEL_SUBSCRIBERS,
}